AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/migrate/**/*'
    - 'test/fixtures/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Style/Encoding:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/SignalException:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
